-- create
CREATE TABLE CLASSMATE (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO CLASSMATE VALUES (0001, 'Clark', 23, 'Moscow');
INSERT INTO CLASSMATE VALUES (0002, 'Dave', 35, 'Kaluga');
INSERT INTO CLASSMATE VALUES (0003, 'Gleb', 46, 'Paris');
INSERT INTO CLASSMATE VALUES (0004, 'Vlad', 24, 'Moscow');
INSERT INTO CLASSMATE VALUES (0005, 'Maks', 20, 'Berlin');
INSERT INTO CLASSMATE VALUES (0006, 'Lina', 30, 'Sochi');
INSERT INTO CLASSMATE VALUES (0007, 'Eve', 30, 'Moscow');
INSERT INTO CLASSMATE VALUES (0008, 'Ava', 18, 'Moscow');


-- fetch 
SELECT name AS ИМЯ 
FROM CLASSMATE 
WHERE address = 'Moscow' AND age >= 18 AND age < 30
